name: CI Runner
permissions:
  checks: write
  actions: read
  contents: read
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 10 17 2 *' # 10am 17 Feb UTC = 2AM PT; standard ddl
jobs:
  run-autograding-tests:
    runs-on: self-hosted
    timeout-minutes: 20
    container: ghcr.io/sfu-cmpt-201/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grader
        uses: SFU-CMPT-201/graders/.github/actions/a8@main
      - name: Autograding Reporter
        uses: SFU-CMPT-201/autograding-grading-reporter@v1
      - name: Clean up
        run: |
          rm -rf ./* ./.* > /dev/null 2>&1 || true
        if: ${{ always() }}
